version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - run:
          name: Install Node dependencies
          command: make node_modules
      - run:
          name: Test
          command: make test
      - store_test_results:
          path: junit
      - run:
          name: Build
          command: make build
